version: '3.7'

services:
    apache:
        build: ./apache
        image: apache_profile_app
        container_name: apache_profile_app
        restart: unless-stopped
        ports:
            - 80:80
        networks:
            - frontend
            - backend
        volumes:
            - ./../:/usr/local/apache2/htdocs
        depends_on:
            - php
            - mysql
    php:
        build: ./php
        image: php_profile_app
        container_name: php_profile_app
        restart: unless-stopped
        networks:
            - backend
        volumes:
            - ./../:/var/www/html
        #this keeps the container running and prevent exit code 0 using tail
        #">" just denotes that command will be multiline
        #command: >
        #    sh -c "composer install --ignore-platform-reqs &&
        #        tail -f /dev/null"

    mysql:
        build: ./mysql
        image: mysql_profile_app
        container_name: mysql_profile_app
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: user
        networks:
            - backend
        volumes:
            - ./database:/var/lib/mysql
            - ./../db_schema:/usr/local/mysql/

networks:
    backend:
    frontend:
